name: Registry and Validation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: write
  pages: write       #Needed if we keep GH pages
  id-token: write    #Needed if we keep GH pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Registry Generator
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python scripts/build-registry.py

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install Node dependencies
        run: npm install

      - name: Build Schematron and SEF files
        run: npm run build

      - name: Check generated files 
        run: |
          FILE="web/eas-registry.xml"
          
          if [ ! -f "$FILE" ]; then
            echo "::error::Validation failed: $FILE is missing!"
            exit 1
          fi
          
          # check if the file is too small (under 1000 bytes)
          FILESIZE=$(stat -c%s "$FILE")
          if [ "$FILESIZE" -lt 1000 ]; then
            echo "::error::Validation failed: $FILE is suspiciously small ($FILESIZE bytes). Possible silent API failure."
            exit 1
          fi

      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add web/*registry.xml web/*.sef.json schematron/*.sch
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "chore: automated registry and sef update [skip ci]"
            
            git pull --rebase origin main
            
            git push
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          ref: main # Pull the version that the 'build' job just updated

      - name: Setup Pages
        uses: actions/configure-pages@v6

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: './web'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5